### ISSUE TITLE
--skip-not-required is not applied if --json option is also provided 

### ISSUE THREAD

**Issue by freeboub** [k-tomoyasu/react-native-oss-license#40]
When using following command

`react-native-oss-license --json --skip-not-required`

the --skip-not-required option is not applied, all dependencies are included in result

**Comment by k-tomoyasu** [comment]
@freeboub Thanks for your pull request!
I have released as version `0.4.1`

**Comment by MarchewkaMatthew** [comment]
Hello @k-tomoyasu, I have a question regarding this issue. I have tried using this command: `react-native-oss-license --json --skip-not-required` to generate the license list for my app, and this problem seems to still exist. I have version **0.7.0** installed. When I checked the generated JSON, I have the same amount of licences listed as without the option. Is there anything I can do to make this option work properly?
